import Footer from "@/components/template/layout/Footer";
import AuthHeader from "@/components/template/layout/header/AuthHeader";
import BottomNavigationBar from "@/components/template/layout/navbar/BottomNavigationBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AuthHeader />
      {children}
      <BottomNavigationBar />
      <Footer />
    </>
  );
}
