import Footer from "@/components/template/layout/Footer";
import ProductDetailHeader from "@/components/template/layout/header/ProductDetailHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ProductDetailHeader />
      {children}
      <Footer />
    </>
  );
}
