import Footer from "@/components/template/layout/Footer";
import MainHeader from "@/components/template/layout/header/MainHeader";
import BottomNavigationBar from "@/components/template/layout/navbar/BottomNavigationBar";
import CategoryTopNavBar from "@/components/template/layout/navbar/CategoryTopNavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: { path: string[] };
  searchParams: { [key: string]: string | string[] | undefined };
}

export default function RootLayout({
  children,
  params: { path },
  searchParams,
}: LayoutProps) {
  const categories = path.map((i) => decodeURI(i));
  const filtering = { ...searchParams, categories };

  return (
    <>
      <MainHeader />
      <CategoryTopNavBar {...{ categories }} />
      {children}
      <BottomNavigationBar />
      <Footer />
    </>
  );
}
