import Footer from "@/components/template/layout/Footer";
import AuthHeader from "@/components/template/layout/header/AuthHeader";
import BrandProductHeader from "@/components/template/layout/header/BrandProductHeader";
import BottomNavigationBar from "@/components/template/layout/navbar/BottomNavigationBar";
import SearchTopNavBar from "@/components/template/layout/navbar/SearchTopNavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: { keyword: string };
}

export default function RootLayout({
  children,
  params: { keyword },
}: LayoutProps) {
  keyword = decodeURI(keyword);

  // const categories = path.map((i) => decodeURI(i));
  // const filtering = { ...searchParams, categories };

  return (
    <>
      <AuthHeader />
      <SearchTopNavBar keywords={keyword} />
      {children}
      <BottomNavigationBar />
      <Footer />
    </>
  );
}
