#!/bin/bash
protected_branches='main develop'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
for protected_branch in $protected_branches; do
    if [ $protected_branch = $current_branch ]; then
        echo "You're about to push protected branch ($(echo $protected_branch))."
        exit 1 # push will not execute
    fi
done

exit 0 # push will execute
